#!/usr/bin/env python

import sys, os

# Use modules in the same dir as wrapper script if present
script_dir = os.path.dirname(os.path.abspath(sys.argv[0]))
sys.path.insert(0, script_dir)

from asl.gui import main
main()
