#!/bin/sh

# ASL_REG: Registration for GRASE-ASL data
#
# Michael Chappell & Brad MacIntosh, FMRIB Image Analysis & Physics Groups
#
# Copyright (c) 2008 University of Oxford
#
# SHCOPYRIGHT

Usage() {
    echo "ASL_REG"
    echo "Version: 1.0"
    echo "Registration for ASL data"
    echo ""
    echo "Usage (optional parameters in {}):"
    echo " -i         : specify input image"
    echo " {-o}       : specify output directory - {default: pwd}"
    echo " -s         : specify structural brain image"
    echo " Extended options (all optional):"
    echo " -t         : specify structural-->standard brain transformation matrix"
    echo " -r         : specify extra low resolution structural image"
    echo " --imat     : specify initial transformation matrix for input to structural image"
    echo "                if supplying a low res. strctural this matrix should refer to that image"
    echo " --inweight : specify weights for input image"
    echo "                same functionality as the flirt -inweight option"
    echo ""
}

#deal with options

if [ -z $1 ]; then
   Usage
   exit 1
fi

until [ -z $1 ]; do
    case $1 in
	-o) outflag=1 outdir=$2
	    shift;;
	-i) inflag=1 infile=$2
	    shift;;
	-s) strucflag=1 struc=$2
	    shift;;
	-t) transflag=1 trans=$2
	    shift;;
	-r) lowstrucflag=1 lowstruc=$2
	    shift;;
	--imat) init=1 inmat=$2
	    shift;;
	--inweight) inweight=$2
	    shift;;
	--zblur) unblur=1
	    ;;
	--flirtsch) flirtsch=$2
	    shift;;
	--debug) debug=1
	    ;;
	*)  Usage
	    echo "Error! Unrecognised option on command line: $1"
	    echo ""
	    exit 1;;
    esac
    shift
done

echo "ASL_REG"
echo "Input file is: $infile"

# set the output name here if not specified
if [ -z $outflag ]; then
    echo "Ouput being placed in input directory"
    outdir=`pwd`;
fi

# Start by looking for the output directory (and create if need be)
if [ ! -d $outdir ]; then
  echo "Creating output directory"
  mkdir $outdir;
fi

# make a temporary directory to work in - delete at end
tmpbase=`$FSLDIR/bin/tmpnam`
if [ -z $debug ]; then
    tempdir=${tmpbase}_asl_reg
else
    tempdir=$outdir/tmp_asl_reg #make local temp directory and do not delete at end
fi
mkdir $tempdir

#deal with init matrix option
if [ ! -z $init ]; then
    inittext="-init $inmat"
fi

# deal with weighting applied to input image
if [ ! -z $inweight ]; then
    weightinstr="-inweight $inweight"
fi

# set the DOF - we will routinely use 6
DOF=6;

# optional flirt schedule for main transformation of asl to structural
if [ -z $flirtsch ]; then
    flirtsch=$FSLDIR/etc/flirtsch/simple3D.sch
else
    echo "Using supplied FLIRT schedule"
fi

echo "Running FLIRT"
if [ -z $lowstrucflag ]; then
    #Step1: 3DOF translation only transformation
    flirt -in $infile -ref $struc -schedule $FSLDIR/etc/flirtsch/xyztrans.sch -omat $tempdir/low2high1.mat -out $tempdir/low2hig1 $inittext $weigthinstr
    #step2: 6DOF transformation with small search region
    flirt -in $infile -ref $struc -dof $DOF -omat $tempdir/low2high.mat -init $tempdir/low2high1.mat  -schedule $flirtsch -out $tempdir/low2high $weigthinstr
else
    #as we have a structural image in perfusion space use it to improve registration
    echo "Using structral image in perfusion space ($lowstruc)"
    #Step1: 3DOF translation only transformation perfusion->lowstruc
    flirt -in $infile -ref $lowstruc -schedule $FSLDIR/etc/flirtsch/xyztrans.sch -omat $tempdir/low2low1.mat $inittext $weigthinstr
    #Step2: 6DOF limited transformation in perfusion space
    flirt -in $infile -ref $lowstruc -dof $DOF -schedule $flirtsch -init $tempdir/low2low1.mat -omat $tempdir/low2low.mat $weigthinstr
    #step3: 6DOF transformation of lowstruc to struc
    flirt -in $lowstruc -ref $struc -omat $tempdir/str2str.mat
    #step4: combine the two transformations
    convert_xfm -omat $tempdir/low2high.mat -concat $tempdir/str2str.mat $tempdir/low2low.mat 
fi

# make the output files
# ASL--> strucutral transformation
cp $tempdir/low2high.mat $outdir/asl2struct.mat
# ASL-->standard transformation (if specified)
if [ ! -z $transflag ]; then
    echo "Combining transformations"
    convert_xfm -omat $outdir/asl2std.mat -concat $trans $tempdir/low2high.mat 
fi

if [ ! -z $lowstrucflag ]; then
# ASL--> low structral transformtaion (if supllied)
    cp $tempdir/low2low.mat $outdir/asl2lowstruct.mat
fi

# remove temporary directory
if [ -z $debug ]; then
    echo "Tidying up"
    rm -r $tempdir
fi



echo "ASL_REG - Done."


